apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-redis
  labels:
    app.kubernetes.io/version: v1.7.0
spec:
  template:
    metadata:
      labels:
        app.kubernetes.io/version: v1.7.0
